import header from '../components/cc-header/cc-header';
import promo from '../components/cc-promo/cc-promo';
import social from '../components/cc-social/cc-social';
import movie from '../components/cc-movie/cc-movie';
import share from '../components/cc-share/cc-share';
import language from '../components/cc-language/cc-language';
import onUs from '../components/cc-on-us/cc-on-us';
import tattoo from '../components/cc-tattoo/cc-tattoo';
import about from '../components/cc-about/cc-about';
import committment from '../components/cc-commitment/cc-commitment';
import product from '../components/cc-product/cc-product';
import buyArea from '../components/cc-buy-area/cc-buy-area';
import shop from '../components/cc-shop/cc-shop';
import footer from '../components/cc-footer/cc-footer';

/* Shared Components */
import bootstrap from '../components/shared/modal/bootstrap.min';
import modal from '../components/shared/modal/modal';
import arrow from '../components/shared/cc-arrow-down/cc-arrow-down';
